//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperFacil.Common.Resource.Multimidia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res_Mul_Midia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res_Mul_Midia() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperFacil.Common.Resource.Multimidia.Res_Mul_Midia", typeof(Res_Mul_Midia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A classificação não é valida.
        /// </summary>
        public static string TagClassificacaoInvalida {
            get {
                return ResourceManager.GetString("TagClassificacaoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de lançamento não é valida.
        /// </summary>
        public static string TagDataLancaInvalido {
            get {
                return ResourceManager.GetString("TagDataLancaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A midia não pode ser duplicada.
        /// </summary>
        public static string TagDuplicado {
            get {
                return ResourceManager.GetString("TagDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A editora não é valida.
        /// </summary>
        public static string TagEditoraInvalida {
            get {
                return ResourceManager.GetString("TagEditoraInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A faixa não foi encontrada.
        /// </summary>
        public static string TagFaixaNotFound {
            get {
                return ResourceManager.GetString("TagFaixaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Genero não é valido.
        /// </summary>
        public static string TagGeneroInvalido {
            get {
                return ResourceManager.GetString("TagGeneroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A midia não é valida.
        /// </summary>
        public static string TagInvalido {
            get {
                return ResourceManager.GetString("TagInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A midia não foi encontrada.
        /// </summary>
        public static string TagNotFound {
            get {
                return ResourceManager.GetString("TagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sub midia não foi encontrada.
        /// </summary>
        public static string TagParentIinvalido {
            get {
                return ResourceManager.GetString("TagParentIinvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tag não foi encontrada.
        /// </summary>
        public static string TagTagNotFound {
            get {
                return ResourceManager.GetString("TagTagNotFound", resourceCulture);
            }
        }
    }
}
