//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperFacil.Common.Resource.Administracao {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res_Adm_Usuario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res_Adm_Usuario() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperFacil.Common.Resource.Administracao.Res_Adm_Usuario", typeof(Res_Adm_Usuario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas são diferentes.
        /// </summary>
        public static string TagSenhaDiferente {
            get {
                return ResourceManager.GetString("TagSenhaDiferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não é valida.
        /// </summary>
        public static string TagSenhaInvalida {
            get {
                return ResourceManager.GetString("TagSenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode ser vazia.
        /// </summary>
        public static string TagSenhaNull {
            get {
                return ResourceManager.GetString("TagSenhaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter de 6 a 20 caracteres.
        /// </summary>
        public static string TagSenhaTamanho {
            get {
                return ResourceManager.GetString("TagSenhaTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuario indicado não é valido.
        /// </summary>
        public static string TagUsuarioInvalido {
            get {
                return ResourceManager.GetString("TagUsuarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuario não pode ser vazio.
        /// </summary>
        public static string TagUsuarioNull {
            get {
                return ResourceManager.GetString("TagUsuarioNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuario deve ter de 4 a 20 caracteres.
        /// </summary>
        public static string TagUsuarioSize {
            get {
                return ResourceManager.GetString("TagUsuarioSize", resourceCulture);
            }
        }
    }
}
